apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world-of-tanks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/sela-tracks/1101/oran/world-of-tanks'
    targetRevision: HEAD
    path: ./wotproj # Path within your repo to the helm chart.
    helm:
      parameters:
        - name: image.repository  # Assuming your Helm values use this key
          value: oranhack7/world_of_tanks_project
        - name: image.tag  # Assuming your Helm values use this key
          value: latest
        - name: image.pullPolicy  # Ensure your Helm chart supports this parameter
          value: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
