version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tanksdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  test: 
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test_tanksdb
    depends_on:
      - mongo

volumes:
  mongo_data:
